name: test
on:
  push:
    branches:
      - main
    tags:
      - v.*.*

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        shell: bash
        run: |
          echo "hello"

